[package]
name = "firefox-session-ui-gpui"
version = "0.1.2"
edition = "2021"
publish = false
license = "Apache-2.0"
repository = "https://github.com/Lej77/firefox-session-ui-gpui"

[features]
default = ["real_data"]

# Disable this feature to see fake data for faster compile times:
real_data = [
    "dep:firefox_session_data",
    "dep:tokio",
    "dep:serde_json",
]

# Support more html to PDF converters (increases binary size):
html_to_pdf_all = ["firefox_session_data?/html_to_pdf_all"]

webview = ["gpui-component/webview", "dep:wry"] # TODO: maybe preview HTML using this

[dependencies]
anyhow = "1"

rfd = "0.15.0" # File prompts
either = "1.11.0" # Used in public API of firefox_session_data
serde_json = { version = "1.0.116", optional = true } # Used to parse session data into the type exported by firefox_session_data
firefox_session_data = { git = "http://github.com/Lej77/firefox_session_data.git", tag = "v0.1.6", optional = true, features = ["windows-gui"] }
raw-window-handle = "0.6.2" # Used to set parent for file prompts (freezes parent window while they are open)

dark-light = "2.0.0" # Fallback when dark theme detection fails

# Windows:
[build-dependencies]
winresource = "0.1.20" # Executable icon on Windows


# Native dependencies
[target.'cfg(not(target_family="wasm"))'.dependencies]
gpui = "0.2.2" # GUI Core
gpui-component = "0.5.1" # GUI Components
gpui-component-assets = "0.5.1" # https://longbridge.github.io/gpui-component/docs/assets
wry = { version = "0.53.3", package = "lb-wry", optional = true } # Web view

tokio = { version = "1.37.0", features = ["rt-multi-thread"], optional = true } # Offload heavy tasks to thread pool

# Web specific dependencies
[target.'cfg(target_family="wasm")'.dependencies]
gpui-git = { package = "gpui", git = "https://github.com/zed-industries/zed" }
gpui-component-git = { package = "gpui-component", git = "https://github.com/longbridge/gpui-component.git" }
gpui-component-assets-git = { package = "gpui-component-assets", git = "https://github.com/longbridge/gpui-component.git" }
# gpui_platform_git = { package = "gpui_platform", git = "https://github.com/zed-industries/zed" }
gpui_web = { package = "gpui_web", git = "https://github.com/zed-industries/zed", default-features = false }


console_error_panic_hook = "0.1"
log ="0.4"
tracing-wasm = "0.2"
console_log = "1.0"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
